// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_AqYWYNnjVqDjiji1Fu8QTgcdFcMeTw',
    appId: '1:629210070387:web:b8f60185fc30a737ce5906',
    messagingSenderId: '629210070387',
    projectId: 'sugaryapp3',
    authDomain: 'sugaryapp3.firebaseapp.com',
    storageBucket: 'sugaryapp3.firebasestorage.app',
    measurementId: 'G-JLL9R7HY07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIwOqB049fWDhB7sIJHnK9ZUxPN5KkXM',
    appId: '1:629210070387:android:db41e80da61e2540ce5906',
    messagingSenderId: '629210070387',
    projectId: 'sugaryapp3',
    storageBucket: 'sugaryapp3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHzExObfpaFiFqrUrJLZuVuDWN1fh18Bo',
    appId: '1:629210070387:ios:93f6722d7f1b99f9ce5906',
    messagingSenderId: '629210070387',
    projectId: 'sugaryapp3',
    storageBucket: 'sugaryapp3.firebasestorage.app',
    iosBundleId: 'com.example.mysugaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHzExObfpaFiFqrUrJLZuVuDWN1fh18Bo',
    appId: '1:629210070387:ios:93f6722d7f1b99f9ce5906',
    messagingSenderId: '629210070387',
    projectId: 'sugaryapp3',
    storageBucket: 'sugaryapp3.firebasestorage.app',
    iosBundleId: 'com.example.mysugaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK_AqYWYNnjVqDjiji1Fu8QTgcdFcMeTw',
    appId: '1:629210070387:web:13754d3c04c4d6b4ce5906',
    messagingSenderId: '629210070387',
    projectId: 'sugaryapp3',
    authDomain: 'sugaryapp3.firebaseapp.com',
    storageBucket: 'sugaryapp3.firebasestorage.app',
    measurementId: 'G-CLLGV6WEJ0',
  );

}